### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by holdbetter** [sergeshustoff/dikt#15]
Hi. I'm trying to explore your PeopleInSpace fork with using IDE plugin and it fails. It breaks file analyzing so it's impossible to navigate in file

IDE: Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023

Could you provide some fixes for it? Is it work on your side?
Also, do you have any contacts? tg or email?

![dikt](https://user-images.githubusercontent.com/47643827/218463334-c94e77d7-a965-4c3e-939d-565ce446949b.jpeg)

**Comment by sergeshustoff** [comment]
I'm working on better API that wouldn't require idea plugin and hacks with code analysis phase. It's in alpha now, I'll update forked sample when it's stable

**Comment by holdbetter** [comment]
Yep, I understand, but it's requires kotlin 1.8, I'm not supposed to upgrade kotlin version in my project now. That's why it's relevant for me

**Comment by sergeshustoff** [comment]
Ok, the I'll think about building a separate build for 1.7.x with new API when it's stable. Also will check wtf is going on with the sample

**Comment by sergeshustoff** [comment]
Ok, so I tried the sample just as is without changing anything. Latest stable AS, dikt plugin 1.0.2 installed and it seems to work just fine without syntax highlighting errors. If you have dikt IDEA plugin installed could you try removing it? Ide will show errors in module classes, but otherwise it should work and compile just fine. If the syntax highlighting error goes away with deleting ide plugin you could try adding `@Suppress("NON_ABSTRACT_FUNCTION_WITH_NO_BODY")` to module to remove those annoying "Function 'X' without a body must be abstract" errors for now and wait for 1.1.0 stable version with better api that doesn't require such hacks

**Comment by sergeshustoff** [comment]
Ok, yes, there is a problem with the last AS version. Will investigate and update plugin. Seems that hack from above should work for now

**Comment by holdbetter** [comment]
Got update. Looks like it fine now. Thanks!
