### ISSUE TITLE
More sample using DI.kt

### ISSUE THREAD

**Issue by holdbetter** [sergeshustoff/dikt#17]
Salam!

I've done my project using DI.kt where it exposes network, navigation, database modules.
It has different implementations and approaches some are basic, some more complicated like sharing router across all modules.
I thought maybe you would you like to add this project as a sample or example of your library. I'll be glad

https://github.com/holdbetter/PremierLeague

It uses old version, because kotlin version is 1.7.21, but I am going to migrate it to K2 later

Also, have to say thank you, library is nice, easy-to-go, chisto na kaife rabotal s nei
Ya kstati tyt pishu, because u menya your contact net

**Comment by sergeshustoff** [comment]
Nice. Will add as example a bit later. Spasibo

**Comment by sergeshustoff** [comment]
Gotovo. Added link to your project in README.md, published 1.1.0 for several kotlin versions and even added contact information in my profile)

Let me know your thoughts on new api - it's a bit different from the old one, but I had to change it to prepare for K2 since some hacks don't work there anymore.
